name: Build and Release on Tag

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller -n "Orientador Vocacional CUCOSTA" --add-data "resources;resources" --noconsole --onefile  __main__.py
        xcopy resources dist\resources /s /i /y
      env:
        PYTHONPATH: ${{ env.PYTHONPATH }}
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: github.event_name == 'push' && github.ref_type == 'tag'
      with:
        tag_name: ${{ startsWith(github.ref, 'refs/tags/v') && replace(github.ref, 'refs/tags/v', '') }}
        release_name: Release ${{ startsWith(github.ref, 'refs/tags/v') && replace(github.ref, 'refs/tags/v', '') }}
        body: |
          Release ${{ startsWith(github.ref, 'refs/tags/v') && replace(github.ref, 'refs/tags/v', '') }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      if: github.event_name == 'push' && github.ref_type == 'tag'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/Orientador_Vocacional_CUCOSTA_${{ inputs.tag_name }}
        asset_name: Orientador_Vocacional_CUCOSTA_${{ inputs.tag_name }}
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
